using Aspose.Email.Live.Demos.UI.Models;
using Aspose.Email.Live.Demos.UI.Models;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Threading.Tasks;

namespace Aspose.Email.Live.Demos.UI.Services.Email
{
    public interface IEmailService
    {
        void RemoveAnnotation(Stream mailStream, string inputFileNameWithExtension, IOutputHandler handler);
        void AssembleFile(Stream input, string shortResourceNameWithExtension, IOutputHandler handler, DataTable dataTable);
        void AssemblyStorageFile(Stream input, string shortResourceNameWithExtension, IOutputHandler handler, DataTable dataTable);
        void AssemblyMailFile(Stream input, string shortResourceNameWithExtension, IOutputHandler handler, DataTable dataTable);
        void AssemblyMboxFile(Stream input, string shortResourceNameWithExtension, IOutputHandler handler, DataTable dataTable);
        void Compare(Stream mail1Stream, Stream mail2Stream, string shortResourceNameWithExtension, IOutputHandler handler);
        void Convert(Stream input, string shortResourceNameWithExtension, IOutputHandler handler, string outputType);
        void ConvertEmlOrMsg(Stream input, string shortResourceNameWithExtension, IOutputHandler handler, string outputType);
        void ConvertEMLToMSG(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMIMEMessageToEML(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMailToMbox(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMailToPst(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertEMLToMHT(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertEmailToHtml(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertEmailToImages(Stream input, string shortResourceNameWithExtension, IOutputHandler handler, string outputType);
        void ConvertEmailToSingleImage(Stream input, string shortResourceNameWithExtension, IOutputHandler handler, string outputType);
        void ConvertEmailToPdf(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertEmailToDoc(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertEmailToPpt(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertEmailToRtf(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertEmailToDocx(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertEmailToDotx(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertEmailToOdt(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertEmailToOtt(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertEmailToEpub(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertEmailToTxt(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertEmailToPs(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertEmailToPcl(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertEmailToXps(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertEmailToEmf(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertEmailToDocm(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertEmailToDotm(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertEmailToMhtml(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMbox(Stream input, string shortResourceNameWithExtension, IOutputHandler handler, string outputType);
        void ConvertMboxToTiff(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToJpg(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToBmp(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToPng(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToSvg(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToHtml(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToMht(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToPst(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToEml(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToMsg(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToPdf(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToDoc(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToPpt(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToRtf(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToDocx(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToDocm(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToDotx(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToDotm(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToOdt(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToOtt(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToEpub(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToTxt(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToEmf(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToXps(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToPcl(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToPs(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertMboxToMhtml(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOst(Stream input, string shortResourceNameWithExtension, IOutputHandler handler, string outputType);
        void ConvertOstToPng(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToBmp(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToJpg(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToTiff(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToSvg(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToHtml(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToMbox(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToMht(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToMsg(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToEml(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOSTToPST(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToPdf(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToDoc(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToPpt(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToRtf(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToDocx(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToDocm(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToDotx(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToDotm(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToOdt(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToOtt(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToEpub(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToTxt(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToEmf(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToXps(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToPcl(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToPs(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertOstToMhtml(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPst(Stream input, string shortResourceNameWithExtension, IOutputHandler handler, string outputType);
        void ConvertPstToMsg(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToMht(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToHtml(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToSvg(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToTiff(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToJpg(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToBmp(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToPng(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToEml(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToMbox(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToPdf(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToDoc(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToPpt(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToRtf(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToDocx(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToDocm(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToDotx(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToDotm(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToOdt(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToOtt(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToEpub(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToTxt(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToEmf(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToXps(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToPcl(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToPs(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ConvertPstToMhtml(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        Task<MailTraceInfo[]> ExtractHeaders(Stream messageStream, bool skipLocal);
        void Merge(IEnumerable<(Stream input, string inputFileNameWithExtension)> inputs, IOutputHandler handler);
        void Parse(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        FileDataResult ParseFileData(Stream input);
        void ExtractAttachments(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void ExtractAttachmentsAsJpgImages(Stream input, string shortResourceNameWithExtension, IOutputHandler handler);
        void Redact(Stream input, string inputFileNameWithExtension, IOutputHandler handler, string searchQuery, string replaceText, bool caseSensitive, bool text, bool comments, bool metadata, string outputType);
        IEnumerable<SearchMatch> Search(Stream input, string pattern);
        void AddDrawingSignature(Stream input, string inputFileNameWithExtension, string imageBase64, string outputType, IOutputHandler handler);
        void AddTextSignature(Stream input, string inputFileNameWithExtension, string text, string textColor, string outputType, IOutputHandler handler);
        void AddTextWatermark(Stream input, string inputFileNameWithExtension, string watermarkText, string fontFamily, string watermarkColor, IOutputHandler handler);
        void AddImageWatermark(Stream input, string inputFileNameWithExtension, byte[] imageBytes, IOutputHandler handler);
        void RemoveWatermark(Stream input, string inputFileNameWithExtension, IOutputHandler handler);
    }
}